# Generated by Django 4.0.2 on 2022-05-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modefied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCodingLanguages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.basemodel')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=('students.basemodel',),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('demographic_gender', models.CharField(max_length=200)),
                ('demographic_nationality', models.CharField(max_length=200)),
                ('social_linkedin', models.URLField()),
                ('social_github', models.URLField()),
                ('employment_company', models.CharField(max_length=200)),
                ('employment_position', models.CharField(max_length=200)),
                ('employment_industry', models.CharField(max_length=200)),
                ('employment_salary', models.IntegerField()),
                ('student_status', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni'), ('Mentor', 'Mentor')], max_length=10, null=True)),
                ('coding_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_languages', to='students.studentcodinglanguages')),
                ('program_attendence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_program_attendance', to='programs.programs')),
            ],
            bases=('students.basemodel',),
        ),
    ]
