# Generated by Django 4.0.2 on 2022-05-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='program_attendence',
        ),
        migrations.AddField(
            model_name='students',
            name='program_attendence',
            field=models.ManyToManyField(related_name='student_program_attendance', to='programs.Programs'),
        ),
    ]
