# Generated by Django 4.0.2 on 2022-05-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_program_attendence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='coding_languages',
        ),
        migrations.AddField(
            model_name='students',
            name='coding_languages',
            field=models.ManyToManyField(related_name='coding_languages', to='students.StudentCodingLanguages'),
        ),
    ]
