# Generated by Django 4.0.2 on 2022-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_students_coding_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='aboriginal_islander',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='demographic_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Nonbinary', 'Non Binary'), ('Bigender', 'Bi Gender'), ('Transgender', 'Trans Gender'), ('Other', 'Other')], max_length=13, null=True),
        ),
    ]
