# Generated by Django 4.0.2 on 2022-05-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('demographic_gender', models.CharField(max_length=200)),
                ('demographic_nationality', models.CharField(max_length=200)),
                ('total_attendance', models.IntegerField()),
                ('program_attendence', models.IntegerField(max_length=200)),
                ('attendee_to_alumni', models.IntegerField()),
                ('alumni_to_mentor', models.IntegerField()),
                ('program_date', models.DateTimeField()),
                ('coding_languages', models.CharField(max_length=200)),
                ('transition_to_tech', models.IntegerField()),
                ('transition_to_other_program', models.IntegerField()),
                ('transition_to_other_study', models.IntegerField()),
            ],
        ),
    ]
