# Generated by Django 4.0.2 on 2022-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='program_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='program_attendence',
            field=models.IntegerField(),
        ),
    ]
