# Generated by Django 4.0.2 on 2022-05-27 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_reports_program_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
